from dataclasses import dataclass, field


@dataclass
class Report:
	title: str
	sections: list[str] = field(default_factory=list)
	include_footer: bool = False


class ReportBuilder:
	def __init__(self, title: str) -> None:
		self._report = Report(title=title)

	def add_section(self, section: str) -> "ReportBuilder":
		self._report.sections.append(section)
		return self

	def with_footer(self) -> "ReportBuilder":
		self._report.include_footer = True
		return self

	def build(self) -> Report:
		return self._report


def make_exporter(format_name: str):
	if format_name == "markdown":
		return lambda report: "\n".join(
			[f"# {report.title}", *[f"- {section}" for section in report.sections]]
			+ (["\nGenerated by starter exporter."] if report.include_footer else [])
		)
	if format_name == "text":
		return lambda report: "\n".join(
			[report.title.upper(), *report.sections]
			+ (["-- starter footer --"] if report.include_footer else [])
		)
	raise ValueError(f"Unknown format: {format_name}")


def main() -> None:
	report = (
		ReportBuilder("Weekly Status")
		.add_section("Completed the adapter cleanup.")
		.add_section("Queued the next refactor.")
		.with_footer()
		.build()
	)
	exporter = make_exporter("markdown")
	print(exporter(report))


if __name__ == "__main__":
	main()
