from dataclasses import dataclass, field
from typing import Protocol

#################
#   CONSTANTS   #
#################

MARKDOWN_FORMAT = "markdown"
TEXT_FORMAT = "text"
SAMPLE_REPORT_TITLE = "Weekly Status"
SAMPLE_REPORT_TAG = "pythonic"
COMPLETED_SECTION = "Completed the adapter cleanup."
NEXT_SECTION = "Queued the next refactor."
MARKDOWN_FOOTER_TEXT = "\nGenerated by the markdown exporter."
TEXT_FOOTER_TEXT = "-- generated by text exporter --"


#############
#   TYPES   #
#############


# Store report content and output options
@dataclass
class Report:
    """Store the title, sections, footer flag, and optional tag"""

    title: str
    sections: list[str] = field(default_factory=list)
    include_footer: bool = False
    tag: str | None = None


# Define the exporter interface used by the factory
class ReportExporter(Protocol):
    """Define the report exporter interface"""

    def export(self, report: Report) -> str:
        """Export the provided report as text"""
        ...


# Export reports in Markdown format
class MarkdownExporter:
    """Build Markdown output from a report"""

    def export(self, report: Report) -> str:
        """Export the provided report as Markdown"""
        lines = [
            f"# {report.title}",
            *[f"- {section}" for section in report.sections],
        ]

        # Include the optional tag when the report provides one
        if report.tag:
            lines.append(f"\nTag: `{report.tag}`")

        # Include the optional footer when requested
        if report.include_footer:
            lines.append(MARKDOWN_FOOTER_TEXT)

        return "\n".join(lines)


# Export reports in plain text format
class TextExporter:
    """Build plain text output from a report"""

    def export(self, report: Report) -> str:
        """Export the provided report as plain text"""
        lines = [report.title.upper(), *report.sections]

        # Include the optional tag when the report provides one
        if report.tag:
            lines.append(f"[{report.tag}]")

        # Include the optional footer when requested
        if report.include_footer:
            lines.append(TEXT_FOOTER_TEXT)

        return "\n".join(lines)


# Build reports through chained method calls
class ReportBuilder:
    """Build a report with a fluent interface"""

    def __init__(self, title: str) -> None:
        """Start a report with the provided title"""
        self._report = Report(title=title)

    def add_section(self, section: str) -> "ReportBuilder":
        """Append a report section and return the builder"""
        self._report.sections.append(section)
        return self

    def tagged(self, tag: str) -> "ReportBuilder":
        """Assign a tag and return the builder"""
        self._report.tag = tag
        return self

    def with_footer(self) -> "ReportBuilder":
        """Enable the footer and return the builder"""
        self._report.include_footer = True
        return self

    def build(self) -> Report:
        """Return the finished report"""
        return self._report


#################
#   FUNCTIONS   #
#################


def make_exporter(format_name: str) -> ReportExporter:
    """Create an exporter for the requested format"""
    exporters: dict[str, ReportExporter] = {
        MARKDOWN_FORMAT: MarkdownExporter(),
        TEXT_FORMAT: TextExporter(),
    }
    return exporters[format_name]


def build_sample_report() -> Report:
    """Build the report used by the lesson demonstration"""
    return (
        ReportBuilder(SAMPLE_REPORT_TITLE)
        .add_section(COMPLETED_SECTION)
        .add_section(NEXT_SECTION)
        .tagged(SAMPLE_REPORT_TAG)
        .with_footer()
        .build()
    )


def main() -> None:
    """Export and print the sample report"""
    report = build_sample_report()
    exporter = make_exporter(MARKDOWN_FORMAT)
    print(exporter.export(report))


if __name__ == "__main__":
    main()
