from dataclasses import dataclass, field
from typing import Protocol


@dataclass
class Report:
	title: str
	sections: list[str] = field(default_factory=list)
	include_footer: bool = False
	tag: str | None = None


class ReportExporter(Protocol):
	def export(self, report: Report) -> str: ...


class MarkdownExporter:
	def export(self, report: Report) -> str:
		lines = [f"# {report.title}", *[f"- {section}" for section in report.sections]]
		if report.tag:
			lines.append(f"\nTag: `{report.tag}`")
		if report.include_footer:
			lines.append("\nGenerated by the markdown exporter.")
		return "\n".join(lines)


class TextExporter:
	def export(self, report: Report) -> str:
		lines = [report.title.upper(), *report.sections]
		if report.tag:
			lines.append(f"[{report.tag}]")
		if report.include_footer:
			lines.append("-- generated by text exporter --")
		return "\n".join(lines)


def make_exporter(format_name: str) -> ReportExporter:
	exporters: dict[str, ReportExporter] = {
		"markdown": MarkdownExporter(),
		"text": TextExporter(),
	}
	return exporters[format_name]


class ReportBuilder:
	def __init__(self, title: str) -> None:
		self._report = Report(title=title)

	def add_section(self, section: str) -> "ReportBuilder":
		self._report.sections.append(section)
		return self

	def tagged(self, tag: str) -> "ReportBuilder":
		self._report.tag = tag
		return self

	def with_footer(self) -> "ReportBuilder":
		self._report.include_footer = True
		return self

	def build(self) -> Report:
		return self._report


def main() -> None:
	report = (
		ReportBuilder("Weekly Status")
		.add_section("Completed the adapter cleanup.")
		.add_section("Queued the next refactor.")
		.tagged("pythonic")
		.with_footer()
		.build()
	)
	exporter = make_exporter("markdown")
	print(exporter.export(report))


if __name__ == "__main__":
	main()
